# Generated by Django 5.2.4 on 2025-07-16 10:34

import shortner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shortCode', models.CharField(default=shortner.models.generate_shortcode, max_length=6, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accessCount', models.IntegerField(default=0)),
            ],
        ),
    ]
